### PR TITLE
Export throttle.

### PR DESCRIPTION
**Pull request by sarahzinger**

### CODE REVIEW

**Comment by jayphelps** [comment]
@sarahzinger :laughing: nice. I've been importing them directly via `import throttle from 'core-decorators/src/throttle';` so I didn't notice this wasn't exported.

Thank you!

**Comment by jayphelps** [comment]
Published as `core-decorators@0.9.1`

**Comment by jayphelps** [comment]
BTW added a test to try and prevent this from happening again by confirming all decorator files were exported correctly.

You can see it here: https://github.com/jayphelps/core-decorators.js/blob/exports-test/test/exports.spec.js

**Comment by sarahzinger** [comment]
Cool! :)

**Pull request merged**
