### PR TITLE
Fix build on windows using cross-env package

### LINKED ISSUE #117: npm run build - fails from Windows command prompt
Looks like the build script update for `es` output causes a failure for the windows platform.   It look to be driven by this line in `package.json`:

```
    "build": "babel --out-dir lib src && BABEL_ENV=es babel --out-dir es src",
```

I gather that starting the second command with `BABEL_ENV=es` is a bash convention for setting a temporary environment variable.  It doesn't work under `Command.exe`.   It seems like a cool feature for a shell, just not found everywhere.

### PR DESCRIPTION
**Pull request by BurtHarris**
Simple enough, fixes #117

### CODE REVIEW

**Comment by BurtHarris** [comment]
Example Appveyor build at https://ci.appveyor.com/project/BurtHarris/core-decorators-js/build/1.0.4

**Comment by jayphelps** [comment]
yay! 🎉  thank you much!!!

**Comment by jayphelps** [comment]
Thank you also for the appveyor setup! Made it really simple: https://ci.appveyor.com/project/jayphelps/core-decorators-js/build/1.0.1

**Comment by BurtHarris** [comment]
Your are welcome @jayphelps.   

But do you have any idea why the [closed pull requests](https://github.com/jayphelps/core-decorators.js/pulls?q=is%3Apr+is%3Aclosed) page shows now a red **x** next to this pull request?

**Comment by jayphelps** [comment]
@BurtHarris travis failed to build when I removed the version bump https://travis-ci.org/jayphelps/core-decorators.js/builds/234977583?utm_source=github_status&utm_medium=notification

> fatal: Couldn't find remote ref refs/pull/118/merge
> Unexpected end of command stream

Dunno why, but presumably just a temporary connection issue to github or something.

**Comment by BurtHarris** [comment]
OK, I see, it failed on Travis.CI, but later succeeded.   

Could you please take a look at https://stackoverflow.com/questions/44037774/requiring-npm-version-4-when-building-a-package-json/44108673 ?  I'm stumped and looking for best practices, you seem like a real expert.

**Comment by jayphelps** [comment]
@BurtHarris Took a look, but I don't have a solution, sorry! Does seem like a tough spot.

**Comment by BurtHarris** [comment]
OK, thanks anyway.   I appreciate it.

**Pull request merged**
