### PR TITLE
Debounce decorator implemented

### PR DESCRIPTION
**Pull request by dfsq**
Implementation of the debounce decorator.

### CODE REVIEW

**Comment by dfsq** [comment]
Didn't notice you removed must dependecy, so now build fails.

**Comment by jayphelps** [comment]
@dfsq updated to no longer use `must. See https://github.com/jayphelps/core-decorators.js/blob/master/src/deprecate.spec.js for reference.

Mostly looks like you just need your `expects` like this:

```js
// expect(editor.counter).to.equal(0);
editor.counter.should.equal(0);
```

**Comment by dfsq** [comment]
Yea, I fixed tests with chai expect.

**Comment by jayphelps** [comment]
Thanks @dfsq!

**Pull request merged**
