### PR TITLE
@before decorator

### PR DESCRIPTION
**Pull request by darul75**
Hi @jayphelps 

I let you decide if it could be relevant to get such a decorator :)

Made for fun.

Kindly,

Julien

### CODE REVIEW

**Comment by girlwithglasses** [comment]
How about adding an 'after' decorator to go with it?

**Comment by darul75** [comment]
I was thinking about it and then thought it would perhaps not be useful ;) but I will add it

**Comment by darul75** [comment]
@girlwithglasses @jayphelps,

I was confused about how to deal with an asynchronous task and would like some help on it.

**@before(functionToBeCalledBefore)**

- functionToBeCalledAfter synchronous: fine, and we just apply decorated one then
- functionToBeCalledAfter asynchronous: I choosed to only support a Promise, any better approach ?

**@after(functionToBeCalledAfter)**

- functionToBeCalledAfter is sync/async :  no matter, we just execute it
- but problem is what if decorated function is doing something async, how to trigger something to tell decorator to execute its functionToBeCalledAfter function ?

**Comment by jayphelps** [comment]
@darul75 sorry about the delay! :frowning: 

Can you describe some real world use cases that this helps solve?

**Comment by jayphelps** [comment]
Closing due to inactivity. Feel free to add some real world use cases and we could discuss further.

**Pull request closed without merging**
