### PR TITLE
Decorators are stage 1

### PR DESCRIPTION
**Pull request by isiahmeadows**
Moreover, they're almost ready to advance to stage 2. [Source](https://github.com/tc39/ecma262).

### CODE REVIEW

**Comment by jayphelps** [comment]
This actually is intentionally listed as `stage-0` because the decorator introduced breaking changes in `stage-1` but no transpiler that I'm aware of implements these new changes yet so this library does not support both implementations at the moment. Let me know if I'm somehow mistaken! 😄

**Comment by isiahmeadows** [comment]
Major breaking changes for stage-1 proposals [are acceptable IIUC](https://tc39.github.io/process-document/), but I think a clear, unmissable disclaimer would be better than any other option I can think of. I'm not that hard-pressed about it, though, and I've found more flexible ways around this problem than what even decorators allow. (For one, separating logic from data helps.)

**Comment by jayphelps** [comment]
@isiahmeadows sorry man, I'm confused. Are you suggesting we say that this library supports stage-0 syntax but the latest spec is stage-1? (Which IMO is implied)

I wasn't complaining about breaking changes in spec, that's obviously natural, expected. Only that there's no point in trying to update this library to support the latest spec since no one implements it yet so it's likely it wouldn't even work correctly since it would be untested (and useless)

**Comment by jayphelps** [comment]
Maybe if you set up a PR with the changes you recommend I'll have a clear idea what you're suggesting?

**Comment by jayphelps** [comment]
Duh, this is a PR. My bad. But AFAIK this only changes stage-0 to stage-1 but that would be incorrect since this lib implements stage-0 syntax. Make sense?

**Comment by isiahmeadows** [comment]
I may update this PR later today (it's late) with these suggestions. But IIUC the syntax so far changed little from the stage-0 syntax (which allowed Aurelia and Angular to prematurely jump the gun).

**Comment by jayphelps** [comment]
Syntax for consuming of decorators didn't change but implementation of decorator functions themselves like this library did very much so.

**Comment by isiahmeadows** [comment]
Could you explain?

**Comment by jayphelps** [comment]
[Decorator signature changed](https://github.com/wycats/javascript-decorators/blob/master/interop/reusability.md#the-decorate-and-property-utilities):

```js
// A Decorator is a function that takes a target and a decorator descriptor and return
// an optional decorator descriptor.
type Decorator = (target: Object, descriptor: DecoratorDescriptor): DecoratorDescriptor;
```

As well as the `DecoratorDescriptor` is [no longer a regular property descriptor shape](https://github.com/wycats/javascript-decorators/blob/master/interop/reusability.md#appendix-decorator-descriptor-list).

**Comment by isiahmeadows** [comment]
That's new to me. I didn't even know that.

**Comment by silkentrance** [comment]
@jayphelps just stumbled over this one, please see wycats/javascript-decorators/issues/70

**Comment by jayphelps** [comment]
Closing due to inactivity and I _believe_ the it's correct as-is since this lib only works with stage-0 syntax. Do let me know if I'm misunderstanding!

**Pull request closed without merging**
